### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by pavondunbar** [Zerobeings/zerb-nft-marketplace#1]
Hello there,

Pavon Dunbar here.

**First, GREAT JOB developing this NFT Marketplace.**  I truly appreciate it and love how the marketplace uses "Proof of Verification" of an NFT before admitting a user into the site.

My question is very simple. Am I allowed to modify your codebase and deploy this in production? I will make sure to give you and the gentleman who developed Factoria / PrivateParty credit in the footer.

Let me know please and thank you once again. If not, I will trash the dev environment immediately.

Not trying to step on anyone's toes or offend anyone.

Wishing you much success,

Pavon

**Comment by CalculatingZero** [comment]
Hello,

Yes, you can use the codebase however you would like!

CalculatingZero
